---
title: 'Recommender Systems - Project #3'
author: "J. Hamski, V. Nguy"
date: "June 28, 2016"
output: html_document
---


```{r, warning=FALSE, message=FALSE, cache=TRUE}
require(shiny)
require(dplyr)
require(ggplot2)
require(tidyr)
require(knitr)
#require(Matrix)
require(recommenderlab)

options(scipen=999)
```

Reading in needed datasets. Artist information will be joined to user-artist dataset for readability
```{r Read_Dataset, cache=TRUE, warnings = FALSE}
user.artists.pairwise <- read.delim('hetrec2011-lastfm-2k/user_artists.dat', sep="\t")

artists <- read.delim('hetrec2011-lastfm-2k/artists.dat', sep="\t") %>%
  select(id, name)
```

#Data Preparation

Converting from Artist IDs to Artist Names for easier interpretation.
```{r join_artist_name, cache=TRUE}
colnames(artists) <- c("artistID", "name")

#note: one duplicate artist
#artists$name[duplicated(artists$name)==TRUE]
user.artists.pairwise <- inner_join(user.artists.pairwise, artists, by="artistID")
user.artists.pairwise <- select(user.artists.pairwise, -artistID)
user.artists.pairwise$name <- strtrim(user.artists.pairwise$name, 100)
user.artists.pairwise[16060,]$name <- NA

#ggplot(user.artists.pairwise, aes(x = weight)) + geom_density() + theme_bw() + scale_x_log10()
```

```{r, cache=TRUE}
num_listens = 1000

user.artists.matrix <- user.artists.pairwise %>%
  filter(weight > num_listens) %>% #filter artists with less than num_listens listens
  spread(key = name, value = weight) %>%
  as.matrix()

user.artists <- user.artists.matrix[,-1]
dim(user.artists)
```

Replace NAs with zeros and scale.
```{r}
user.artists[is.na(user.artists)] <- 0
user.artists <- scale(user.artists)
user.artists[is.nan(user.artists)] <- 0
```

Built-in SVD
```{r}
svd <- svd(user.artists)
summary(svd$d)
```

```{r}
svd$d[51:length(svd$d)] <- 0

#UDVT
user.artists.svd <- svd$u %*% diag(svd$d) %*% t(svd$v)
dim(user.artists.svd)
```


```{r}
user.artists.RRM <- as(user.artists.svd,"realRatingMatrix")
user.ratings <- user.artists.RRM[rowCounts(user.artists.RRM) > 45, colCounts(user.artists.RRM) > 50]

#dim(user.ratings)

#user.ratings.norm <- normalize(user.ratings)

#sum(rowMeans(user.ratings.norm) > 0.00001)
```

```{r}
training <- sample(x=c(TRUE, FALSE), size=nrow(user.ratings), replace=TRUE, prob=(c(0.8,0.2)))
rating.train <- user.ratings[training,]
rating.test <- user.ratings[!training,]
```

```{r}
rec.model <- Recommender(data=rating.train, method="IBCF", parameter = list(k=5))
```

```{r}
rec.predict <- predict(object=rec.model, newdata=rating.test, n=5)
rec.predict@items[6]

rec_1 <- rec.predict@items[[1]]
artist.predict <- rec.predict@itemLabels[rec_1]
artist.predict
```
